spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: rootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3308/preorder
  data:
    redis:
      port: '6379'
      host: localhost
server:
  port: '8082'
